language: python

python:
  - "3.7"

before_install:
  - pip install tox-travis

stages:
  - test

jobs:
  include:
    - stage: test
      name: "Test Backend"
      script:
        - cd backend && make test
