service: xadrez

frameworkVersion: '>=1.28.0 <2.0.0'

plugins:
  - serverless-finch

provider:
  name: aws
  runtime: go1.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

  environment:
    WEBSITE_S3_BUCKET: xadrez-website-${self:provider.stage}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  connect:
    handler: bin/lambda/websocket/connect
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: bin/lambda/websocket/disconnect
    events:
      - websocket:
          route: $disconnect

custom:
  client:
    bucketName: ${self:provider.environment.WEBSITE_S3_BUCKET}
    distributionFolder: frontend/public
