service: xadrez-backend

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: python3.7

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

  environment:
    AUTH0_DOMAIN: dev-embzl7vs.auth0.com
    AUTH0_CLIENT_ID: brSV94G2uZANc2lmTtZYXUmci2pTdx1H
    AUTH0_JWKS_URL: https://${self:provider.environment.AUTH0_DOMAIN}/.well-known/jwks.json
    PLAYERS_TABLE: Players-${self:provider.stage}
    GAMES_TABLE: Games-${self:provider.stage}
    CONNECTION_ID_INDEX: ConnectionIdIndex

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PLAYERS_TABLE}

    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PLAYERS_TABLE}/index/${self:provider.environment.CONNECTION_ID_INDEX}

    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.GAMES_TABLE}

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy: []
  serverless-offline:
    port: 5000

functions:
  auth:
    handler: src/lambdas/auth/auth0.handler
    cors: true

  connect:
    handler: src/lambdas/websocket/connect.handler
    events:
      - websocket:
          authorizer:
            name: auth
            type: request
            identitySource:
              - route.request.querystring.token
          route: $connect

  disconnect:
    handler: src/lambdas/websocket/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  default:
    handler: src/lambdas/websocket/default.handler
    events:
      - websocket:
          route: $default

  createGame:
    handler: src/lambdas/websocket/createGame.handler
    events:
      - websocket:
          route: createGame

  acceptGame:
    handler: src/lambdas/websocket/acceptGame.handler
    events:
      - websocket:
          route: acceptGame

  rejectGame:
    handler: src/lambdas/websocket/rejectGame.handler
    events:
      - websocket:
          route: rejectGame

  getPlayers:
    handler: src/lambdas/http/getPlayers.handler
    events:
      - http:
          method: get
          path: players
          authorizer: auth
          cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

    PlayersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: connection_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.PLAYERS_TABLE}
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.CONNECTION_ID_INDEX}
            KeySchema:
            - AttributeName: connection_id
              KeyType: HASH
            Projection:
              ProjectionType: ALL

    GamesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.GAMES_TABLE}
