service: xadrez-backend

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: python3.7

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy: []
  serverless-offline:
    port: 5000

functions:
  connect:
    handler: lambda/websocket/connect.handler
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: lambda/websocket/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  default:
    handler: lambda/websocket/default.handler
    events:
      - websocket:
          route: $default
